services:
  database:
    image: postgres:16-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./backend/db-config:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    user: '$UID:$GID'
    ports:
      - ${PGADMIN_DEFAULT_PORT}:80
    volumes:
      - ./backend/docker-data/pgadmin-data:/var/lib/pgadmin
